CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,organization_id TEXT,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS oauth_clients(id TEXT PRIMARY KEY,organization_id TEXT,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS organizations(id TEXT PRIMARY KEY,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS organization_members(organization_id TEXT,user_id TEXT,active INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(organization_id,user_id));
CREATE TABLE IF NOT EXISTS permissions(id TEXT PRIMARY KEY,resource_type TEXT,action TEXT,UNIQUE(resource_type,action));
CREATE TABLE IF NOT EXISTS roles(id TEXT PRIMARY KEY,name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS role_permissions(role_id TEXT,permission_id TEXT,PRIMARY KEY(role_id,permission_id));
CREATE TABLE IF NOT EXISTS subject_user_roles(subject_type TEXT,subject_id TEXT,user_id TEXT,role_id TEXT,PRIMARY KEY(subject_type,subject_id,user_id,role_id));
CREATE TABLE IF NOT EXISTS groups(id TEXT PRIMARY KEY,subject_type TEXT,subject_id TEXT,name TEXT);
CREATE TABLE IF NOT EXISTS group_members(group_id TEXT,user_id TEXT,PRIMARY KEY(group_id,user_id));
CREATE TABLE IF NOT EXISTS group_roles(group_id TEXT,role_id TEXT,PRIMARY KEY(group_id,role_id));
CREATE TABLE IF NOT EXISTS user_permission_overrides(subject_type TEXT,subject_id TEXT,user_id TEXT,permission_id TEXT,effect TEXT CHECK(effect IN('allow','deny')),PRIMARY KEY(subject_type,subject_id,user_id,permission_id));
CREATE TABLE IF NOT EXISTS client_grants(client_id TEXT,subject_type TEXT,subject_id TEXT,permission_id TEXT,active INTEGER DEFAULT 1,PRIMARY KEY(client_id,subject_type,subject_id,permission_id));
CREATE TABLE IF NOT EXISTS user_consents(user_id TEXT,client_id TEXT,subject_type TEXT,subject_id TEXT,permission_id TEXT,active INTEGER DEFAULT 1,PRIMARY KEY(user_id,client_id,subject_type,subject_id,permission_id));
CREATE TABLE IF NOT EXISTS subject_features(subject_type TEXT,subject_id TEXT,feature_key TEXT,enabled INTEGER,PRIMARY KEY(subject_type,subject_id,feature_key));
CREATE TABLE IF NOT EXISTS subject_subscriptions(subject_type TEXT,subject_id TEXT,plan_key TEXT,status TEXT,valid_until TEXT,PRIMARY KEY(subject_type,subject_id));
CREATE TABLE IF NOT EXISTS plan_features(plan_key TEXT,feature_key TEXT,enabled INTEGER DEFAULT 1,PRIMARY KEY(plan_key,feature_key));
CREATE TABLE IF NOT EXISTS plan_quotas(plan_key TEXT,quota_key TEXT,quota_limit INTEGER,PRIMARY KEY(plan_key,quota_key));
CREATE TABLE IF NOT EXISTS quota_counters(subject_type TEXT,subject_id TEXT,quota_key TEXT,quota_limit INTEGER,used INTEGER DEFAULT 0,reserved INTEGER DEFAULT 0,PRIMARY KEY(subject_type,subject_id,quota_key),CHECK(quota_limit IS NULL OR used+reserved<=quota_limit));
CREATE TABLE IF NOT EXISTS quota_ledger(id INTEGER PRIMARY KEY,idempotency_key TEXT,subject_type TEXT,subject_id TEXT,grant_id TEXT DEFAULT '',quota_key TEXT,amount INTEGER,operation TEXT,UNIQUE(idempotency_key,subject_type,subject_id,grant_id,quota_key,operation));
CREATE TABLE IF NOT EXISTS quota_reservations(id TEXT,subject_type TEXT,subject_id TEXT,grant_id TEXT DEFAULT '',quota_key TEXT,amount INTEGER,status TEXT,expires_at TEXT,PRIMARY KEY(id,subject_type,subject_id,grant_id,quota_key));
CREATE TABLE IF NOT EXISTS authorization_policies(id TEXT,version INTEGER,active INTEGER DEFAULT 1,PRIMARY KEY(id,version));
CREATE TABLE IF NOT EXISTS policy_nodes(id TEXT PRIMARY KEY,policy_id TEXT,policy_version INTEGER,parent_id TEXT,node_type TEXT,rule_type TEXT,config_json TEXT DEFAULT '{}',position INTEGER);
CREATE TABLE IF NOT EXISTS endpoint_bindings(id TEXT PRIMARY KEY,method TEXT,route_template TEXT,resource_loader TEXT,intent_resolver TEXT,resource_type TEXT,action TEXT,policy_id TEXT,policy_version INTEGER,active INTEGER DEFAULT 1,UNIQUE(method,route_template));
CREATE TABLE IF NOT EXISTS organization_access_grants(id TEXT PRIMARY KEY,owner_organization_id TEXT,grantee_organization_id TEXT,resource_type TEXT,resource_id TEXT,action TEXT,valid_from TEXT,valid_until TEXT,status TEXT,allow_subdelegation INTEGER DEFAULT 0,created_by TEXT,CHECK(owner_organization_id<>grantee_organization_id));
CREATE TABLE IF NOT EXISTS organization_feature_grants(access_grant_id TEXT,feature_key TEXT,PRIMARY KEY(access_grant_id,feature_key));
CREATE TABLE IF NOT EXISTS organization_quota_allocations(access_grant_id TEXT,quota_key TEXT,allocated INTEGER,used INTEGER DEFAULT 0,reserved INTEGER DEFAULT 0,PRIMARY KEY(access_grant_id,quota_key),CHECK(used+reserved<=allocated));
CREATE TABLE IF NOT EXISTS invoices(id TEXT PRIMARY KEY,organization_id TEXT,owner_id TEXT,approver_id TEXT,status TEXT,amount INTEGER,region TEXT,system INTEGER DEFAULT 0,version INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS idempotency_records(key TEXT PRIMARY KEY,request_hash TEXT,response_json TEXT);
CREATE TABLE IF NOT EXISTS audit_events(id INTEGER PRIMARY KEY,actor_id TEXT,resource_id TEXT,action TEXT,policy_id TEXT,policy_version INTEGER);
